spring.profiles.active: local

server.port: 8080


spring.thymeleaf:
    cache: false

spring.template.cache: false

      
#management.port: 8080 
#management.address: 127.0.0.1
#management.context-path: /details
 
#endpoints.health.enabled: true

#management.security.enabled: true
    
#security.basic.enabled: true

#security.user.name: admin
#security.user.password: jejadle

#management:
#  security:
#    enabled: true
#management:
#  shell:
#    auth:
#      simple:
#        user:
#          name: user
#          password: jejadle





---
spring:
  profiles: local

server.port: 8080

#Connection
spring.datasource:
  url: jdbc:mysql://localhost:3306/retreat
  username: retreat
  password: retreat
  driver-class-name: com.mysql.jdbc.Driver
  testOnBorrow: true
  validationQuery: SELECT 1

spring.jpa:
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy #org.hibernate.cfg.DefaultNamingStrategy
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect    
    show-sql: false
    properties.hibernate.format_sql: false

logging:
  file: logs/application.log
  level:
    org.thymeleaf: INFO
    org.springframework.web: INFO
    #org.hibernate.SQL: INFO
    org.jejadle.retreat.core.service: DEBUG
    

spring.thymeleaf:
    cache: false

spring.template.cache: false

security:
  user.name: admin 
  user.password: 1111 
  user.role: USER 

---
spring:
  profiles: dev

server.port: 80

#Connection
spring.datasource:
  url: jdbc:mysql://db:3306/retreat  
  username: retreat
  password: retreat
  driver-class-name: com.mysql.jdbc.Driver
  testOnBorrow: true
  validationQuery: SELECT 1

spring.jpa:
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy #org.hibernate.cfg.DefaultNamingStrategy
    hibernate.ddl-auto: update
    properties.hibernate.dialect: org.hibernate.dialect.MySQL5InnoDBDialect    
    show-sql: false

logging:
  file: /var/log/pas_application.log    


spring.thymeleaf:
    cache: false


---
spring:
  profiles: real

#Connection
spring.datasource:
  url: jdbc:h2:mem:test #변경필요
  username: sa
  password:
  driver-class-name: org.h2.Driver #org.mariadb.jdbc.Driver

spring.jpa:
    hibernate.naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties.hibernate.dialect: org.hibernate.dialect.H2Dialect #org.hibernate.dialect.MySQL5InnoDBDialect
